//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab4_Bondareva.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lab4Table
    {
        public int ID { get; set; }
        public string Name_ { get; set; }
        public string Message_ { get; set; }
    }
}
